model_list:
  - model_name: ollama-codellama
    litellm_params:
      model: ollama/codellama
      api_base: "http://pluto.fritz.box:11434"

litellm_settings:
  # Enable caching with Redis
  cache: true
  cache_params:
    type: "redis"
    host: "redis"  # Using the service name from docker-compose
    port: 6379
    # No password by default as per your redis config
  
  # Logging settings
  verbose: true
  
  # Default model
  default_model: ollama-codellama

# Server configuration
server:
  host: 0.0.0.0
  port: 8080
