model_list:
  - model_name: ollama-codellama
    litellm_params:
      model: ollama/codellama
      api_base: "http://pluto.fritz.box:11434"

litellm_settings:
  # Disable caching to simplify troubleshooting
  cache: false
  
  # Logging settings
  verbose: true
  
  # Default model
  default_model: ollama-codellama

# Server configuration
server:
  host: 0.0.0.0
  port: 8080
